[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 0.4
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0
