[env]
TERM = "alacritty"

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.7
startup_mode = "Windowed"

[window.padding]
x = 16
y = 16
