#!/bin/bash

echo "Welcome torija!, Let's setup"
echo "=== Updating packages"
sudo apt-get update
sudo apt-get install curl -y

# Setup ohmyzsh

echo "=== ZSH"

if [[ -z $(which zsh) ]]; then
    echo "====== Installing zsh"
    sudo apt-get install zsh -y
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    chsh -s $(which zsh) $(whoami)
else
    echo "====== zsh already installed in $(which zsh)"
fi

# Install utilities

echo "=== Utilities"
sudo apt-get install stow fzf ack tig tmux neovim terraform -y

# Set .dotfiles 

echo "=== .dotfiles"
pushd $HOME/.dotfiles
for folder in zsh
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
