#!/bin/bash

echo "Welcome torija!, Let's setup"

# Check OS

echo "=== What are we working on?"
if [ -f "/etc/os-release" ]; then
    . /etc/os-release
    if [ "$NAME" = "Ubuntu" ] && grep -q "20.04" <<< "$VERSION"; then
        echo "====== Let's start installing everying for $NAME:$VERSION"
    else
        echo "====== We have no setup instructions for this place"
        exit 0
    fi
else
    echo "No /etc/os-release found"
    exit 0
fi

# Terraform setup

if [ -z "$(which terraform)"]; then
    echo "=== Terraform key and repository"
    wget -O- https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        sudo tee /etc/apt/sources.list.d/hashicorp.list
fi

# Terraform setup

echo "=== Updating packages"
sudo add-apt-repository ppa:neovim-ppa/stable -y
sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
if [[ $(which tfswitch) != "/usr/local/bin/tfswitch" ]]; then
    echo "====== Installing tfswitch"
curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash
else
    echo "====== tfswitch already installed in $(which tfswitch)"
fi

# Setup ohmyzsh

echo "=== ZSH"

if [[ $(which zsh) != "/usr/bin/zsh" ]]; then
    echo "====== Installing zsh"
    sudo apt-get install zsh -y
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    chsh -s $(which zsh) $(whoami)
else
    echo "====== zsh already installed in $(which zsh)"
fi

# Install utilities

echo "=== Utilities"
sudo apt-get install stow fzf ripgrep ack tig tmux neovim terraform fonts-powerline -y
sudo apt install python3-dev python3-pip python3-setuptools -y
pip3 install thefuck --user

# Install LSPs

echo "=== LSPs"
sudo apt-get install terraform-ls -y
npm install -g typescript-language-server typescript

# Set .dotfiles 

echo "=== .dotfiles"
for folder in zsh nvim tmux
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done

# Setup TMUX

echo "=== TMUX"
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    echo "====== Downloading tpm"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
echo "====== Loading tmux conf"
tmux source $HOME/.tmux.conf

