#!/bin/bash

echo "Welcome torija!, Let's setup"

# Terraform setup

if [[ $(which terraform) != "/usr/bin/terraform" ]]; then
    echo "=== Terraform key and repository"
    wget -O- https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        sudo tee /etc/apt/sources.list.d/hashicorp.list
fi

# Terraform setup

echo "=== Updating packages"
sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
sudo apt-get install curl -y

# Setup ohmyzsh

echo "=== ZSH"

if [[ $(which zsh) != "/usr/bin/zsh" ]]; then
    echo "====== Installing zsh"
    sudo apt-get install zsh -y
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    chsh -s $(which zsh) $(whoami)
else
    echo "====== zsh already installed in $(which zsh)"
fi


# Install utilities

echo "=== Utilities"
sudo apt-get install stow fzf ack tig tmux neovim terraform -y

# Set .dotfiles 

echo "=== .dotfiles"
for folder in zsh
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done

